# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    providers:
        in_memory:
            memory:
              users:
                admin: { password: 123, roles:['ROLE_ADMIN']}
                god: { password: 123, roles: ['ROLE_SUPER_ADMIN']}

        customer_provider:
            entity:
                class: ModelBundle:Customer
                property: email

    #Encodage des mots de passe
    encoders:
      Symfony\Component\Security\Core\User\User: plaintext
      ModelBundle\Entity\Customer:
        algorithm: bcrypt

    role_hierarchy:
      ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
          pattern: ^/admin
          anonymous: false
          provider: in_memory
          form_login:
            login_path: admin_login_page
            check_path: admin_login_check
            default_target_path: /admin
          logout:
            path: admin_logout
            target: homepage

        customer:
          pattern: ^/
          anonymous: true
          provider: customer_provider
          form_login:
            login_path: customer_login_page
            check_path: customer_login_check
            default_target_path: customer_account
          logout:
            path: customer_logout
            target: homepage

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access-control:
      - { path: ^/admin, roles: ROLE_ADMIN}
