<?php

namespace ModelBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * ArtistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllArtistAndPaginate($page) {
        $qb = $this->createQueryBuilder("a")
            ->select(['a', 'n'])
            ->innerJoin('a.nationality', 'n')
            ->orderBy('a.name');
        $query = $qb->getQuery();

        $maxResults = 10;

        $firstResult = ($page - 1) * $maxResults;
        $query->setFirstResult($firstResult)->setMaxResults($maxResults);

        $paginator = new Paginator($query);

        if (($paginator->count() <= $firstResult) && $page != 1) {
            throw new NotFoundHttpException("La page demandée n'existe pas");
        }

        return $paginator;

    }
}
