<?php

namespace ModelBundle\Repository;

/**
 * CustomerCreditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerCreditRepository extends \Doctrine\ORM\EntityRepository
{
}
