<?php

namespace ModelBundle\Repository;

/**
 * CustomerReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerReviewRepository extends \Doctrine\ORM\EntityRepository
{
}
