<?php

namespace ModelBundle\Repository;

/**
 * MovieCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
