<?php

namespace ModelBundle\Repository;

/**
 * PressTitleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PressTitleRepository extends \Doctrine\ORM\EntityRepository
{
}
