<?php

namespace ModelBundle\Repository;

/**
 * PressReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PressReviewRepository extends \Doctrine\ORM\EntityRepository
{
}
