<?php

namespace ModelBundle\Repository;

/**
 * rentalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rentalRepository extends \Doctrine\ORM\EntityRepository
{
}
